# ------ dataset_path ------
data_path: './HAM10000/'
root_path: './'

init_Zeta: 1
init_epsilon: 1
init_beta: 1
# ------ Hyperparamters ------
alpha: 0.5

search_scale: [10,1, 50]

load_cache: False
load_pre_feat: False
search_hp: True
# ------ Basic Config ------
dataset: 'ham10000'

lr: 0.001
train_epoch: 100
batch_size: 64

num_classes: 7

num_threads: 8
save_interval: 50

cache_dir: './model/clip'

# ------ Dalle Dataset -----
# dalle_dataset: 'dalle_ham10000'
# dalle_shots: [2,2,2,2,2]

gpt3_prompt_file: './gpt_file/ham10000_prompt.json'
gpt3_prompt: True